# Use the image built from your current Dockerfile as the base
FROM docker.robotsix.net/dev-docker:latest

# Install python3-colcon-common-extensions and rosdep
# Switch to root user
USER root

RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-rosdep && \
    rm -rf /var/lib/apt/lists/* && \
    rosdep init

# Switch back to 'robotsix-docker' user
USER robotsix-docker

# Update rosdep
RUN rosdep update
