ARG UBUNTU_VERSION=latest
FROM docker.robotsix.net/dev-docker:${UBUNTU_VERSION}-colcon-tools

# Switch to root user
USER root



RUN apt-get update && apt-get install -y --no-install-recommends \
	ros-humble-desktop \
	rm -rf /var/lib/apt/lists/*
    

# Switch back to 'robotsix-docker' user
USER robotsix-docker

