ARG UBUNTU_VERSION=latest
FROM robotsix/dev-docker:${UBUNTU_VERSION}

# Install python3-colcon-common-extensions and rosdep
# Switch to root user
USER root

# Add ROS 2 repository and import GPG key
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    echo "deb [arch=$(dpkg --print-architecture)] http://repo.ros2.org/ubuntu/main $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2-latest.list

# Install python3-colcon-common-extensions and python3-rosdep
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions \
    python3-rosdep && \
    rm -rf /var/lib/apt/lists/* && \
    rosdep init

# Switch back to 'robotsix-docker' user
USER robotsix-docker

