ARG UBUNTU_VERSION=latest
FROM robotsix/dev-docker:${UBUNTU_VERSION}-colcon-tools
ARG UBUNTU_VERSION

# Switch to root user
USER root

RUN if [ ${UBUNTU_VERSION} = "latest" ]; then \
        ROS_DISTRO=jazzy; \
	else \
	ROS_DISTRO=humble; \
	fi && \
	apt-get update && apt-get install -y --no-install-recommends \
	ros-${ROS_DISTRO}-desktop \
	ros-${ROS_DISTRO}-plotjuggler-ros && \
	rm -rf /var/lib/apt/lists/*
    

# Switch back to 'robotsix-docker' user
USER robotsix-docker

