# Use the image built from your current Dockerfile as the base
FROM robotsix-docker

# Install python3-colcon-common-extensions and rosdep
RUN sudo apt-get update && sudo apt-get install -y \
    python3-colcon-common-extensions \
    python3-rosdep && \
    sudo rm -rf /var/lib/apt/lists/*
