name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [22.04, 20.04, latest]
        include_colcon_tools: [false, true]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.robotsix.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Dockerfile
        id: determine_dockerfile
        run: |
          if [ "${{ matrix.include_colcon_tools }}" = "true" ]; then
            echo "dockerfile=Dockerfile-colcon-tools" >> $GITHUB_OUTPUT
          else
            echo "dockerfile=Dockerfile" >> $GITHUB_OUTPUT
          fi

      - name: Generate Tags
        id: generate_tags
        run: |
          TAG="docker.robotsix.net/dev-docker:${{ matrix.ubuntu_version }}"
          if [ "${{ matrix.include_colcon_tools }}" = "true" ]; then
            TAG="${TAG}-colcon-tools"
          fi
          echo "tags=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ steps.determine_dockerfile.outputs.dockerfile }}
          build-args: UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: ${{ steps.generate_tags.outputs.tags }}
