name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [22.04, latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Dockerfile
        id: determine_dockerfile
        run: |
          echo "dockerfile=Dockerfile" >> $GITHUB_OUTPUT

      - name: Generate Tags
        id: generate_tags
        run: |
          TAG="robotsix/dev-docker:${{ matrix.ubuntu_version }}"
          echo "tags=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ steps.determine_dockerfile.outputs.dockerfile }}
          build-args: UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: ${{ steps.generate_tags.outputs.tags }}

  build_colcon:
    runs-on: ubuntu-latest
    needs: build_base
    strategy:
      matrix:
        ubuntu_version: [22.04, latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Dockerfile
        id: determine_dockerfile
        run: |
          echo "dockerfile=Dockerfile-colcon-tools" >> $GITHUB_OUTPUT

      - name: Generate Tags
        id: generate_tags
        run: |
          TAG="robotsix/dev-docker:${{ matrix.ubuntu_version }}-colcon-tools"
          echo "tags=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ steps.determine_dockerfile.outputs.dockerfile }}
          build-args: UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: ${{ steps.generate_tags.outputs.tags }}

  build_ros2:
    runs-on: ubuntu-latest
    needs: build_colcon
    strategy:
      matrix:
        ubuntu_version: [22.04, latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Dockerfile
        id: determine_dockerfile
        run: |
          echo "dockerfile=Dockerfile-ros2" >> $GITHUB_OUTPUT

      - name: Generate Tags
        id: generate_tags
        run: |
          TAG="robotsix/dev-docker:${{ matrix.ubuntu_version }}-ros2"
          echo "tags=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ steps.determine_dockerfile.outputs.dockerfile }}
          build-args: UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: ${{ steps.generate_tags.outputs.tags }}

  build_gz:
    runs-on: ubuntu-latest
    needs: build_ros2
    strategy:
      matrix:
        ubuntu_version: [22.04, latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Dockerfile
        id: determine_dockerfile
        run: |
          echo "dockerfile=Dockerfile-ros2-gz" >> $GITHUB_OUTPUT

      - name: Generate Tags
        id: generate_tags
        run: |
          TAG="robotsix/dev-docker:${{ matrix.ubuntu_version }}-gz"
          echo "tags=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ steps.determine_dockerfile.outputs.dockerfile }}
          build-args: UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: ${{ steps.generate_tags.outputs.tags }}
